// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syzpeilbyukqvuedbpzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5enBlaWxieXVrcXZ1ZWRicHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTc2MjUsImV4cCI6MjA2ODkzMzYyNX0.TuRB7UHPfnsdw1b9Zl7x0ByiGOz1aWt347NEq3VU014";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});